WITH SUB AS(
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "MiLK"
)

SELECT DISTINCT C.CART_ID 
FROM CART_PRODUCTS C
JOIN SUB S
ON S.CART_ID = C.CART_ID
WHERE C.NAME = "Yogurt"

