WITH SUB AS (
        SELECT HOST_ID
        FROM PLACES
        GROUP BY HOST_ID
        HAVING COUNT(HOST_ID) >= 2
)
    
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
JOIN SUB S
ON P.HOST_ID = S.HOST_ID
ORDER BY 1;