WITH SUB AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN SUB S 
ON F.CATEGORY = S.CATEGORY AND F.PRICE = S.MAX_PRICE
ORDER BY MAX_PRICE DESC;